version: '3'
services:
  web:

    build: .

    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3001:3001
    depends_on:
      - db

    tty: true

    stdin_open: true
  db:
    image: postgres
    platform: linux/amd64
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-volume: